name: Deploy Static Files on SFTP Server
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"  
      - name: Upload Files
        uses: Team-One-Developers/sftp_deploy_action@0.0.2
        with:
          host: "161.35.125.23"
          username: root
          password: aTlas00z
          localPath: "."
          remotePath: "/usr/share/nginx/html/" 
          cleanBefore: true
      - name: play command
        run: mkdir /usr/share/nginx/html/sss
